<div class="floatleft">Dzisiaj</div>
<div class="floatright"><?php echo $counter->d; ?></div>
<div class="cl"></div>
<div class="floatleft">W tym roku</div>
<div class="floatright"><?php echo $counter->y; ?></div>
<div class="cl"></div>
<div class="floatleft">Od 2000r.</div>
<div class="floatright"><?php echo $counter->o; ?></div>
<div class="cl"></div>